### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by dineshks1** [comment]
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,For more info tag @gerrith3.

**Comment by dineshks1** [comment]
Please review this merge.

**Comment by epoberezkin** [comment]
Sorry, travis is discontinuing their .org and it’s too long to wait even with 3 jobs...

I’m moving everything to GitHub actions, but I would rather not run matrix builds on all platform combinations (e.g. I’m using Linux, Mac and Windows myself but the builds run only Linux with different node versions, as different node versions are more likely to introduce some variance into the test results than different platforms) - it is better to detect platform specific issues  on users CI sites, otherwise it would slow down PR testing too much

**Comment by gerrith3** [comment]
Travis has announced about 2 years ago that they are merging all CI services into travis-ci.COM from travis-ci.ORG.  They have slowed down .ORG to encourage people to migrate before they shut it down.  However, they are still fully supporting free CI (and it is much faster on .com!)  GitHub Actions has no support for ppc64le, s390x and possibly arm, and I don't think they have a MacOS build service either.  I think if you re-registered with travis-ci.COM you'd find that the slowness went away and you'd have more options and flexibility.

As far as testing on other platforms, we just had a major retailer find a package was built for another arcihtecture had an embedded intel based jar file in it.  That led to a very embarrasing hard fail that would have been caught with testing like this.

**Pull request closed without merging**
