### PR TITLE
equal(NaN, NaN) → true (like Object.is)

### LINKED ISSUE #6: NaN
Should `equal(NaN, NaN)` return `true`?

### PR DESCRIPTION
**Pull request by langpavel**
Fix #6

### CODE REVIEW

**Comment by langpavel** [comment]
This may be semver major:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#Browser_compatibility

**Comment by langpavel** [comment]
@MadRabbit Whole point is that two `NaN`s are **not** equal :-)
Try yourself:
```
langpavel@lang:~$ node
> NaN === NaN
false
```

**Comment by MadRabbit** [comment]
yeah, i get that. my point is that you're replacing `===` with `Object.is` which will slow the thing down. maybe there is a way to keep `===` as the first check for regular values, and then check for NaNs after that

**Comment by langpavel** [comment]
As mentioned in https://github.com/epoberezkin/fast-deep-equal/issues/6#issuecomment-382360360, plofill for `Object.is` looks like that:
```js
    if (x === y) { // Ref check
      // check for +0 != -0
      return x !== 0 || 1 / x === 1 / y;
    } else {
      // check NaN == NaN
      return x !== x && y !== y;
    }
```
It also solve `+0` and `-0` **non**equivalence. Zero is zero, we are operating in integer and real numbers set, not in [hyperreals](https://en.wikipedia.org/wiki/Hyperreal_number)
```js
-0 !== 0 // false
-0 == 0 // true
```
Hand on :hearts:, this library is used to see if two values are structurally equivalent so this cases should be treated this way…

**Comment by langpavel** [comment]
@MadRabbit back to you, polyfill will be one day really slower than `Object.is`…
`Object.is` is primitive much more natural to machine than loosy `==` and may be/may be not more natural than `===`

**Comment by langpavel** [comment]
Whoops :slightly_smiling_face: 
```js
-0 !== 0  // false
-0 === 0  // true
-0  == 0   // true
-0  != 0   // false
Object.is(-0,0) // false
```

**Comment by langpavel** [comment]
@MadRabbit Support is pretty good, except IE11 and some server side engines:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#Browser_compatibility
- http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.is

**Comment by langpavel** [comment]
Related reading: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_samenes

**Comment by MadRabbit** [comment]
Well if its not broadly supported it shouldnt be in a library then.

Have you looked at how a polyfill looks like for the feature? Maybe backporting that would make more sense

**Comment by langpavel** [comment]
I cited polyfill 4 hours ago

**Comment by MadRabbit** [comment]
right. seems like you did, so why don't you port it into your PR then?

**Comment by langpavel** [comment]
Hi @MadRabbit, I created 2 nice commits, one for `equal(NaN, NaN)` → `true`,
second commit is only test — spec

**Comment by langpavel** [comment]
#### Benchmark :muscle: 
```
fast-deep-equal         122,360 ops/sec   ±0.96% (88 runs sampled)
nano-equal               74,972 ops/sec   ±0.76% (87 runs sampled)
shallow-equal-fuzzy     100,578 ops/sec   ±2.10% (88 runs sampled)
underscore.isEqual       72,798 ops/sec   ±0.85% (86 runs sampled)
lodash.isEqual           18,979 ops/sec  ±12.61% (81 runs sampled)
deep-equal               26,534 ops/sec   ±0.81% (88 runs sampled)
deep-eql                 15,943 ops/sec   ±1.09% (83 runs sampled)
assert.deepStrictEqual      843 ops/sec   ±1.25% (88 runs sampled)
```
**The fastest is fast-deep-equal**

#### Notable differences
```
nano-equal arrays pseudo array and equivalent array are not equal TypeError: a.every is not a function
    at eqArray (…/node_modules/nano-equal/src/index.js:17:18)
    at nanoEqual (…/node_modules/nano-equal/src/index.js:126:20)
    at Object.<anonymous> (…/benchmark/index.js:31:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
different result nano-equal RegExp objects not equal RegExp objects (different pattern)
different result nano-equal RegExp objects not equal RegExp objects (different flags)
different result nano-equal RegExp objects RegExp and object are not equal
different result shallow-equal-fuzzy objects empty array and empty object are not equal
different result shallow-equal-fuzzy Date objects not equal date objects
different result shallow-equal-fuzzy Date objects date and object are not equal
different result shallow-equal-fuzzy RegExp objects not equal RegExp objects (different pattern)
different result shallow-equal-fuzzy RegExp objects not equal RegExp objects (different flags)
different result shallow-equal-fuzzy RegExp objects RegExp and object are not equal
different result underscore.isEqual scalars 0 and -0 are equal
different result deep-equal scalars 1 and true are not equal
different result deep-equal scalars 0 and false are not equal
different result deep-equal scalars NaN and NaN are equal
different result deep-equal objects empty array and empty object are not equal
different result deep-equal Date objects date and object are not equal
different result deep-equal RegExp objects not equal RegExp objects (different pattern)
different result deep-equal RegExp objects not equal RegExp objects (different flags)
different result deep-equal RegExp objects RegExp and object are not equal
different result deep-eql scalars 0 and -0 are equal
different result assert.deepStrictEqual scalars NaN and NaN are equal
```

**Comment by langpavel** [comment]
@MadRabbit Can you look at, please?

**Comment by MadRabbit** [comment]
looks pretty neat to me

**Comment by epoberezkin** [comment]
NaN equal to NaN: nano-equal, shallow-equal-fuzzy, underscore.isEqual, lodash.isEqual, deep-eql, ramda.equal
NaN not equal to NaN: deep-equal, assert.deepStrictEqual

So it should be change here.

**Comment by langpavel** [comment]
Thanks

**Pull request merged**
