### PR TITLE
Add tests for functions

### PR DESCRIPTION
**Pull request by chrisbolin**
*Thank you so much for the library.* It's really help us out with some performance bottlenecks!

Currently `fast-deep-equal` considers all functions to be empty objects, and that's totally fine by me! I just wanted to codify that with tests. That way if it that behavior ever changed in the future it would (hopefully!) trigger a major version bump, as it's an API change.

### CODE REVIEW

**Comment by epoberezkin** [comment]
@chrisbolin, before legitimising this "feature" it would be good to understand what is the most common behaviour among other packages...

**Comment by epoberezkin** [comment]
I agree, i.e. if it’s the same function. I suspect it could have been introduced by the recent refactoring; if so, it just needs to be fixed.

If it’s always been like this, other packages can be run against the opposite test and if all/most packages treat different functions as non-equal (and I suspect they do), this has to be changed and a major version released.

I don’t think the current behaviour should be tested for, quite the opposite.

**Comment by chrisbolin** [comment]
@epoberezkin totally agree! i'm glad i brought up the issue then. (for our use-case it's nice to ignore functions and treat them as equal, so I'm going to just lock in this version of fast-deep-equal). If you'd like I can change this PR to test the _desired_ behavior. It will fail right now but will be fixed when you change the implementation.

**Comment by epoberezkin** [comment]
@chrisbolin yes. Still need to check when it happened...

**Comment by epoberezkin** [comment]
Different functions are not equal in all other packages

**Pull request closed without merging**
