### PR TITLE
Change non-equality operators to XOR where possible

### PR DESCRIPTION
**Pull request by dchan3**
I know this probably would compromise the readability of the code, but if your objective is to be the fastest of them all, there will be sacrifices you will need to make.

Thank you for your consideration.

### CODE REVIEW

**Comment by dchan3** [comment]
I'm running macOS El Capitan 64-bit on a 2014 MacBook Pro consisting of an Intel Core i5 running at 2.8 GHz with 2 cores total.

**Comment by epoberezkin** [comment]
I meant what the node version? Do you see the difference consistently?

**Comment by dchan3** [comment]
I'm running Node 10. The difference fluctuates with every run shortly after the one before it, so sometimes `nano-equal` will appear to be as fast or faster, although I do get `fast-deep-equal` as the fastest most of the time.

**Comment by dchan3** [comment]
The results of the benchmark tests on my latest commit generally indicate that `fast-deep-equal` was the fastest.

**Pull request closed without merging**
