### PR TITLE
TypeScript support

### PR DESCRIPTION
**Pull request by look-at-this**
You now can `import` typed `equal` in TypeScript code instead of using untyped `require`

```
import * as equal from 'fast-deep-equal';
```

### CODE REVIEW

**Comment by epoberezkin** [comment]
Thank you @look-at-this. Please add the test for .d.ts file with `tsc --target ES5 --noImplicitAny lib/index.d.ts`.

See https://github.com/epoberezkin/ajv/blob/master/package.json#L21

**Comment by look-at-this** [comment]
@epoberezkin, done ✔️

**Comment by epoberezkin** [comment]
I think should they be in package.json files too... I will add

**Comment by look-at-this** [comment]
it's already there https://github.com/epoberezkin/fast-deep-equal/pull/2/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10

**Comment by epoberezkin** [comment]
> it's already there
@look-at-this no, I mean in "files" property of package.json - or it won't be published I think

**Comment by jonaskello** [comment]
Could this be merged please?

**Comment by nickbreaton** [comment]
Does anything else need to be done to get this merged?

**Comment by epoberezkin** [comment]
looking...

**Comment by epoberezkin** [comment]
`npm run test-ts` should run as part of `npm test`

**Comment by Jontem** [comment]
So close... If i could i would have finished it.

**Pull request merged**
